name: CI

on:
  pull_request: {}
  push:
    branches:
      - main
  schedule:
    - cron: '8 10 * * 6'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.64
    - run: cargo build --lib --no-default-features
    - run: cargo build --lib --all-features

  features:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        args:
          - ""
          - "--no-default-features"
          - "--no-default-features --features alloc"
          - "--no-default-features --features alloc,std"
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo build ${{matrix.args}}

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test --all-targets --all-features
    - run: cargo test --doc --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - run: cargo clippy --all-features --lib -- -D warnings -D clippy::pedantic
    - run: cargo clippy --all-features --all-targets -- -D warnings -D clippy::pedantic -A clippy::incompatible_msrv

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - run: cargo fmt --check

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - run: cargo doc
      env:
        RUSTFLAGS: --cfg docsrs
        RUSTDOCFLAGS: --cfg docsrs -D warnings
